In [7]:
import numpy as np
a1 = np.array([[1, 2, 3, 4] , [5, 6, 7, 8]], dtype = float)
a1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [2]:
import numpy as np
a3 = np.array([[[11, 12, 13], [21, 22, 23]], [[31, 32, 33], [41, 42, 44]]]); a3

array([[[11, 12, 13],
        [21, 22, 23]],

       [[31, 32, 33],
        [41, 42, 44]]])

In [6]:
import numpy as np
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
a3[0,1,2]

6

In [28]:
a2 = np.array([[1,2,3], [4,5,6]])
a2.shape

(2, 3)

In [3]:
import numpy as np
a2 = np.array([[1,2,3], [4,5,6]])
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
a2 = np.array([[1,2,3], [4,5,6]])
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
n1 = np.array([[1,2,3], [4,5,6]])
n2 = np.array([7,8])
n1_2 = np.concatenate((n1, n2), axis = None)
n1_2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
import numpy as np
n1 = np.array([[1,2], [4,5]])
n2 = np.array([[7,8]])
n1_2_row = np.concatenate((n1, n2), axis = 0)
n1_2_row

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
a11 = np.array([[1, 2], [3, 4]])
a12 = np.array([[5, 6]])
a11_12_row = np.concatenate((a11, a12), axis=0)
a11_12_row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# solve regression through matrix algebra

In [4]:
a11 = np.array([[1, 2, 8], [3, 4, 10]])
a12 = np.array([[5, 6]])
a11_12_column = np.concatenate((a11.T, a12), axis=0)
a11_12_column

array([[ 1,  3],
       [ 2,  4],
       [ 8, 10],
       [ 5,  6]])

In [7]:
a2 = np.array([[11, 12, 13, 14], [21, 22, 23, 24]]); a2.T

array([[11, 21],
       [12, 22],
       [13, 23],
       [14, 24]])

In [13]:
a11 = np.array([[1, 2], [3, 4]])
a11.T

array([[1, 3],
       [2, 4]])

In [30]:
n1 = np.array([1,23,4])
n2 = np.array([56,7,8])
n12 = np.concatenate((n1,n2)).reshape(2,3)
n12

array([[ 1, 23,  4],
       [56,  7,  8]])

In [23]:
a11 = np.array([[1, 2], [3, 4]])
a12 = np.array([[5, 6]])
a11_12_column = np.vstack((a11, a12))
a11_12_column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
n1 = np.array([1,23,4])
n2 = np.array([56,7,8])
n12 = np.concatenate((n1,n2)).reshape(2,3)
np.std(n12, axis=1)

array([ 9.7410928 , 22.86676385])

In [8]:
n1 = np.array([1,23,4])
n2 = np.array([56,7,8])
n12 = np.concatenate((n1,n2)).reshape(2,3)
np.corrcoef(n1,n2)

array([[ 1.        , -0.61903739],
       [-0.61903739,  1.        ]])

In [9]:
from numpy import linalg as npla
a8 = np.array([[1, 2], [2, 3]]); a9 = np.array([4, 7]) # Eq1 : x + 2y = 4 | Eq2 : 2x + 3y = 7
npla.solve(a8, a9)

array([2., 1.])

In [58]:
import pandas as pd
my_series1 = ['a', 'b', 'c', 'd'] 
ps1 = pd.Series(my_series1); ps1
my_series2 = {'a': 12, 'b': 34, 'c': 56} 
ps2 = pd.Series(my_series2); ps2



a    12
b    34
c    56
dtype: int64

In [56]:
my_series2 = {'a': 12, 'b': 34, 'c': 56} 
ps2 = pd.Series(my_series2); ps2
ps2['b']

34

In [59]:
my_data = {
    'Name': ['Alexa', 'Bixby', 'Cortana', 'Jarvis', 'Lyra', 'Robin', 'Siri'], 
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'], 
    'Education': ['Postgraduate', 'Graduate', 'Postgraduate', 'Doctorate', 'Graduate', 'Graduate', 'Postgraduate'], 
    'Age': [24, 21, 25, 28, 23, 22, 24], 
    'Monthly_Salary': [27000, 25000, 30000, 35000, 26000, 24000, 28000]
    }
my_df = pd.DataFrame(my_data); my_df

Name  Gender     Education  Age  Monthly_Salary
0    Alexa  Female  Postgraduate   24           27000
1    Bixby    Male      Graduate   21           25000
2  Cortana  Female  Postgraduate   25           30000
3   Jarvis    Male     Doctorate   28           35000
4     Lyra  Female      Graduate   23           26000
5    Robin    Male      Graduate   22           24000
6     Siri  Female  Postgraduate   24           28000

In [60]:
my_df.to_excel('my_excel_file.xlsx', index=False)

In [65]:
my_df.sort_values('Monthly_Salary')

Name  Gender     Education  Age  Monthly_Salary
5    Robin    Male      Graduate   22           24000
1    Bixby    Male      Graduate   21           25000
4     Lyra  Female      Graduate   23           26000
0    Alexa  Female  Postgraduate   24           27000
6     Siri  Female  Postgraduate   24           28000
2  Cortana  Female  Postgraduate   25           30000
3   Jarvis    Male     Doctorate   28           35000

In [4]:
import pandas as pd
my_data = {
    'Name': ['Alexa', 'Bixby', 'Cortana', 'Jarvis', 'Lyra', 'Robin', 'Siri'], 
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'], 
    'Education': ['Postgraduate', 'Graduate', 'Postgraduate', 'Doctorate', 'Graduate', 'Graduate', 'Postgraduate'], 
    'Age': [24, 21, 25, 28, 23, 22, 24], 
    'Monthly_Salary': [27000, 25000, 30000, 35000, 26000, 24000, 28000]
    }
my_df = pd.DataFrame(my_data)
my_df

Name  Gender     Education  Age  Monthly_Salary
0    Alexa  Female  Postgraduate   24           27000
1    Bixby    Male      Graduate   21           25000
2  Cortana  Female  Postgraduate   25           30000
3   Jarvis    Male     Doctorate   28           35000
4     Lyra  Female      Graduate   23           26000
5    Robin    Male      Graduate   22           24000
6     Siri  Female  Postgraduate   24           28000

In [5]:
my_df.sort_values('Monthly_Salary')

Name  Gender     Education  Age  Monthly_Salary
5    Robin    Male      Graduate   22           24000
1    Bixby    Male      Graduate   21           25000
4     Lyra  Female      Graduate   23           26000
0    Alexa  Female  Postgraduate   24           27000
6     Siri  Female  Postgraduate   24           28000
2  Cortana  Female  Postgraduate   25           30000
3   Jarvis    Male     Doctorate   28           35000

In [7]:
my_df.iloc[0]

Name                     Alexa
Gender                  Female
Education         Postgraduate
Age                         24
Monthly_Salary           27000
Name: 0, dtype: object

In [8]:
my_df.loc[0, 'Name']

'Alexa'

In [10]:
my_df[(my_df['Age'] < 25) & (my_df['Education'] == 'Graduate')] 

Name  Gender Education  Age  Monthly_Salary
1  Bixby    Male  Graduate   21           25000
4   Lyra  Female  Graduate   23           26000
5  Robin    Male  Graduate   22           24000

In [13]:
my_df.groupby('Education')['Monthly_Salary'].mean()

Education
Doctorate       35000.000000
Graduate        25000.000000
Postgraduate    28333.333333
Name: Monthly_Salary, dtype: float64

In [19]:
my_df_pivot = pd.pivot_table(my_df, index='Gender', columns='Education', values='Monthly_Salary', aggfunc='max'); my_df_pivot


Education  Doctorate  Graduate  Postgraduate
Gender                                      
Female           NaN   26000.0       30000.0
Male         35000.0   25000.0           NaN

In [16]:
panel_data = {
    'Company': ['ABC', 'ABC', 'DEF', 'DEF', 'GHI', 'GHI'],
    'Year': [2001, 2002, 2001, 2002, 2001, 2002],
    'Revenue': [1234, 2345, 3456, 4567, 5678, 6789]
    }
panel_df = pd.DataFrame(panel_data); panel_df


Company  Year  Revenue
0     ABC  2001     1234
1     ABC  2002     2345
2     DEF  2001     3456
3     DEF  2002     4567
4     GHI  2001     5678
5     GHI  2002     6789

In [17]:
panel_df_pivot = pd.pivot(panel_df, index='Company', columns='Year', values='Revenue'); panel_df_pivot

Year     2001  2002
Company            
ABC      1234  2345
DEF      3456  4567
GHI      5678  6789

In [20]:
panel_df_pivot.reset_index(level='Company', inplace=True); panel_df_pivot

Year Company  2001  2002
0        ABC  1234  2345
1        DEF  3456  4567
2        GHI  5678  6789

In [21]:
panel_df_pivot_melt =  pd.melt(panel_df_pivot, id_vars=['Company'], value_name='Revenue'); panel_df_pivot_melt

Company  Year  Revenue
0     ABC  2001     1234
1     DEF  2001     3456
2     GHI  2001     5678
3     ABC  2002     2345
4     DEF  2002     4567
5     GHI  2002     6789

In [24]:
import numpy as np
a11 = np.array([[1, 2], [3, 4]])
a11

array([[1, 2],
       [3, 4]])

In [25]:
import numpy as np
a11 = np.array([[1, 2], [3, 4]])
a11.T

array([[1, 3],
       [2, 4]])

In [27]:
a12 = np.array([[5, 6]])
a12.T

array([[5],
       [6]])

In [1]:
import pandas as pd
panel_data = {
    'Company': ['ABC', 'ABC', 'DEF', 'DEF', 'GHI', 'GHI'],
    'Year': [2001, 2002, 2001, 2002, 2001, 2002],
    'Revenue': [1234, 2345, 3456, 4567, 5678, 6789]
    }
panel_df = pd.DataFrame(panel_data); panel_df
panel_df

Company  Year  Revenue
0     ABC  2001     1234
1     ABC  2002     2345
2     DEF  2001     3456
3     DEF  2002     4567
4     GHI  2001     5678
5     GHI  2002     6789

In [2]:
panel_df_pivot = pd.pivot(panel_df, index='Company', columns='Year', values='Revenue'); panel_df_pivot

Year     2001  2002
Company            
ABC      1234  2345
DEF      3456  4567
GHI      5678  6789

In [3]:
panel_df_pivot.reset_index(level='Company', inplace=True); panel_df_pivot


Year Company  2001  2002
0        ABC  1234  2345
1        DEF  3456  4567
2        GHI  5678  6789

In [4]:
panel_df_pivot_melt =  pd.melt(panel_df_pivot, id_vars=['Company'], value_name='Revenue'); panel_df_pivot_melt


Company  Year  Revenue
0     ABC  2001     1234
1     DEF  2001     3456
2     GHI  2001     5678
3     ABC  2002     2345
4     DEF  2002     4567
5     GHI  2002     6789

In [5]:
my_data = {
    'Name': ['Alexa', 'Bixby', 'Cortana', 'Jarvis', 'Lyra', 'Robin', 'Siri'], 
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'], 
    'Education': ['Postgraduate', 'Graduate', 'Postgraduate', 'Doctorate', 'Graduate', 'Graduate', 'Postgraduate'], 
    'Age': [24, 21, 25, 28, 23, 22, 24], 
    'Monthly_Salary': [27000, 25000, 30000, 35000, 26000, 24000, 28000]
    }
my_df = pd.DataFrame(my_data); my_df

Name  Gender     Education  Age  Monthly_Salary
0    Alexa  Female  Postgraduate   24           27000
1    Bixby    Male      Graduate   21           25000
2  Cortana  Female  Postgraduate   25           30000
3   Jarvis    Male     Doctorate   28           35000
4     Lyra  Female      Graduate   23           26000
5    Robin    Male      Graduate   22           24000
6     Siri  Female  Postgraduate   24           28000

In [6]:
my_df_f = my_df[my_df['Gender'] == 'Female']; my_df_f

Name  Gender     Education  Age  Monthly_Salary
0    Alexa  Female  Postgraduate   24           27000
2  Cortana  Female  Postgraduate   25           30000
4     Lyra  Female      Graduate   23           26000
6     Siri  Female  Postgraduate   24           28000

In [7]:
my_df_m = my_df[my_df['Gender'] != 'Female']; my_df_m

Name Gender  Education  Age  Monthly_Salary
1   Bixby   Male   Graduate   21           25000
3  Jarvis   Male  Doctorate   28           35000
5   Robin   Male   Graduate   22           24000

In [8]:
my_df_fm = pd.concat([my_df_f, my_df_m], ignore_index=True); my_df_fm

Name  Gender     Education  Age  Monthly_Salary
0    Alexa  Female  Postgraduate   24           27000
1  Cortana  Female  Postgraduate   25           30000
2     Lyra  Female      Graduate   23           26000
3     Siri  Female  Postgraduate   24           28000
4    Bixby    Male      Graduate   21           25000
5   Jarvis    Male     Doctorate   28           35000
6    Robin    Male      Graduate   22           24000

In [9]:
my_df_merged_left = pd.merge(my_df_f[['Education', 'Age']], my_df_m[['Education', 'Monthly_Salary']], on='Education', how='left'); my_df_merged_left

Education  Age  Monthly_Salary
0  Postgraduate   24             NaN
1  Postgraduate   25             NaN
2      Graduate   23         25000.0
3      Graduate   23         24000.0
4  Postgraduate   24             NaN

In [10]:
my_df_merged_inner = pd.merge(my_df_f[['Education', 'Age']], my_df_m[['Education', 'Monthly_Salary']], on='Education', how='inner'); my_df_merged_inner

Education  Age  Monthly_Salary
0  Graduate   23           25000
1  Graduate   23           24000